name: Release

on:
  push:
    branches: [ main ]
    
env:
  productNamespacePrefix: "Splat"

jobs:
  release:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-release.yml@main
    with:
      productNamespacePrefix: "Splat"
    secrets:
      SIGN_CLIENT_USER_ID: ${{ secrets.SIGN_CLIENT_USER_ID }}
      SIGN_CLIENT_SECRET: ${{ secrets.SIGN_CLIENT_SECRET }}
      SIGN_CLIENT_CONFIG: ${{ secrets.SIGN_CLIENT_CONFIG }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
