name: Release

on:
  push:
    branches: [ main ]
    
env:
  productNamespacePrefix: "Splat"

jobs:
  release:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-release.yml@main
    with:
      productNamespacePrefix: "Splat"
    secrets:
      SIGN_ACCOUNT_NAME: ${{ secrets.SIGN_ACCOUNT_NAME }}
      SIGN_CLIENT_SECRET: ${{ secrets.SIGN_CLIENT_SECRET }}
      SIGN_CLIENT_CONFIG: ${{ secrets.SIGN_CLIENT_CONFIG }}
      AZURE_CRED: ${{ secrets.AZURE_CRED }}
